const GLOBE_RSS="https://www.globenewswire.com/RssFeed/orgclass/1/feedTitle/GlobeNewswire%20-%20News%20about%20Public%20Companies";
const PR_RSS="https://www.prnewswire.com/rss/news-releases-list.rss";

const HTML=String.raw\`<!doctype html><html lang="ar" dir="rtl"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>📰 ماسح الأخبار</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#07111f;color:#eef4ff;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Tahoma,Arial,sans-serif}.wrap{max-width:1050px;margin:auto;padding:22px}.head,.stat,.card{background:#0d1b2d;border:1px solid #1e3550;border-radius:18px}.head{padding:20px;margin-bottom:16px}h1{margin:0 0 8px;font-size:28px}.sub,.meta,#status{color:#9eb1c9}.bar{margin-top:16px}button{border:0;border-radius:12px;padding:12px 18px;background:#1769e0;color:#fff;font-weight:700;font-size:15px}.stats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:16px 0}.stat{text-align:center;padding:14px}.num{display:block;font-size:22px;font-weight:800;margin-top:5px}.card{padding:16px;margin:11px 0}.top{display:flex;justify-content:space-between;gap:10px}.ticker{font-size:20px;font-weight:900}.pill{display:inline-block;padding:4px 9px;border-radius:999px;background:#172941;margin-right:6px;font-size:12px}.pos{background:#103b2a;color:#6ee7a5}.neg{background:#4a1e27;color:#ff9eac}.hot{background:#513b12;color:#ffd978}.title{font-size:18px;font-weight:800;margin:10px 0;line-height:1.5}.summary{color:#c3cfde;line-height:1.7}.link{display:inline-block;margin-top:10px;color:#78b4ff;text-decoration:none}.empty{padding:30px;text-align:center;color:#9eb1c9}@media(max-width:650px){.stats{grid-template-columns:1fr}.top{flex-direction:column}}
</style></head><body><main class="wrap">
<section class="head"><h1>📰 ماسح الأخبار</h1><div class="sub">أخبار الشركات الأمريكية للأسهم من $1 إلى $7 — الأحدث أولًا</div><div class="bar"><button id="refresh">🔄 تحديث الأخبار</button></div></section>
<section class="stats"><div class="stat">مطابقة السعر<span id="count" class="num">—</span></div><div class="stat">آخر ساعة<span id="hour" class="num">—</span></div><div class="stat">أخبار ساخنة<span id="hot" class="num">—</span></div></section>
<div id="status">جارٍ التحميل...</div><section id="list"></section></main>
<script>
const $=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
const age=ts=>{const m=Math.max(0,Math.floor((Date.now()-ts)/60000));if(m<1)return"الآن";if(m<60)return m+" د";if(m<1440)return Math.floor(m/60)+" س";return Math.floor(m/1440)+" يوم"};
function tone(s){s=(s||"").toLowerCase();const p=["fda","approval","approved","clearance","contract","agreement","acquisition","merger","partnership","award","order","launch","results","guidance","revenue","earnings"];const n=["offering","dilution","reverse split","bankruptcy","default","delisting","investigation","fraud","lawsuit","guidance cut"];const pos=p.some(x=>s.includes(x)),neg=n.some(x=>s.includes(x));return pos&&!neg?["إيجابي","pos"]:neg&&!pos?["سلبي","neg"]:["محايد",""];}
async function load(){const b=$("refresh");b.disabled=true;$("status").textContent="جارٍ جلب أحدث الأخبار...";try{const r=await fetch("/api/news?ts="+Date.now(),{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.error||"فشل الطلب");$("count").textContent=d.stats.matching;$("hour").textContent=d.stats.lastHour;$("hot").textContent=d.stats.hot;if(!d.items.length){$("list").innerHTML='<div class="empty">لا توجد أخبار مطابقة حاليًا.</div>'}else{$("list").innerHTML=d.items.map(x=>{const t=tone(x.headline+" "+x.summary);return '<article class="card"><div class="top"><div><span class="ticker">$'+esc(x.symbol)+'</span><span class="pill">'+esc(x.source)+'</span><span class="pill">'+age(x.datetime*1000)+'</span></div><div><span class="pill '+t[1]+'">'+t[0]+'</span>'+(x.hot?'<span class="pill hot">🔥 ساخن</span>':"")+'</div></div><div class="title">'+esc(x.headline)+'</div><div class="meta">السعر: $'+Number(x.price).toFixed(2)+'</div><div class="summary">'+esc(x.summary)+'</div><a class="link" href="'+esc(x.url||"#")+'" target="_blank" rel="noopener">فتح المصدر ↗</a></article>'}).join("")}$("status").textContent="آخر تحديث: "+new Date().toLocaleTimeString("ar-SA")}catch(e){$("status").textContent="خطأ: "+e.message}$("refresh").disabled=false}
$("refresh").onclick=load;load();setInterval(load,300000);
</script></body></html>\`;

function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json;charset=UTF-8","cache-control":"no-store"}})}
function num(v){const n=Number(String(v??"").replace(/[$,% ,]/g,""));return Number.isFinite(n)?n:0}
function clean(s){return String(s||"").replace(/<!\\[CDATA\\[([\\s\\S]*?)\\]\\]>/g,"$1").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;|&apos;/g,"'").replace(/<[^>]+>/g," ").replace(/\\s+/g," ").trim()}
function field(b,n){const m=b.match(new RegExp("<(?:[\\\\w-]+:)?"+n+"(?:\\\\s[^>]*)?>([\\\\s\\\\S]*?)</(?:[\\\\w-]+:)?"+n+">","i"));return m?clean(m[1]):""}
function link(b){const m=b.match(/<link[^>]+href=["']([^"']+)["'][^>]*>/i);return m?clean(m[1]):clean(field(b,"link")||field(b,"guid"))}
function symbols(text,u){const s=new Set(),t=clean(text);let m;for(const re of [/\b(?:NASDAQ|NYSE|NYSEAMERICAN|AMEX|OTCQX|OTCQB):\s*([A-Z]{1,6})\b/gi,/\\$([A-Z]{1,6})\b/g])while((m=re.exec(t)))s.add(m[1].toUpperCase());const p=/\\(([A-Z]{1,6})\\)/g;while((m=p.exec(t)))if(u.has(m[1]))s.add(m[1]);return [...s].filter(x=>u.has(x))}
function catalyst(t){t=t.toLowerCase();return ["fda","approval","approved","clearance","clinical","phase 1","phase 2","phase 3","trial","contract","agreement","partnership","collaboration","acquisition","acquire","merger","license","licensing","order","purchase order","award","launch","milestone","earnings","revenue","guidance","forecast","results","data","study","patent","uplisting","compliance","financing","offering","private placement","registered direct","atm","sec","10-k","10-q","8-k","dividend","buyback","repurchase","strategic","investment","funding","debt","restructuring","bankruptcy","default","delisting","investigation","lawsuit","settlement","recall","resigns","appoints","ceo","cfo","manufacturing","production"].some(x=>t.includes(x))}
function bad(t){t=t.toLowerCase();return ["stocks to watch","stocks moving","top gainers","top losers","market roundup","market update","market recap","market movers","premarket movers","pre-market movers","after-hours movers","price target","stock analysis","technical analysis","investor alert","why shares","trending:"].some(x=>t.includes(x))}
async function rows(exchange){const r=await fetch("https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=500&offset=0&exchange="+exchange+"&download=true",{headers:{"accept":"application/json","origin":"https://www.nasdaq.com","referer":"https://www.nasdaq.com/market-activity/stocks/screener","user-agent":"Mozilla/5.0"}});if(!r.ok)throw Error("NASDAQ HTTP "+r.status);const d=await r.json();return Array.isArray(d?.data?.rows)?d.data.rows:[]}
async function feed(url,source){try{const r=await fetch(url,{headers:{"user-agent":"KhalidStockNews/1.0","accept":"application/rss+xml,application/xml,text/xml,*/*"}});if(!r.ok)return[];const xml=await r.text();return [...xml.matchAll(/<(?:item|entry)\\b[^>]*>([\\s\\S]*?)<\\/(?:item|entry)>/gi)].map(m=>{const b=m[1],headline=clean(field(b,"title")),summary=clean(field(b,"description")||field(b,"summary")||field(b,"content")),pub=field(b,"pubDate")||field(b,"published")||field(b,"updated"),ts=Date.parse(pub);return {headline,summary,url:link(b),datetime:Number.isFinite(ts)?Math.floor(ts/1000):0,raw:b,source}}).filter(x=>x.headline&&x.datetime)}catch{return[]}}
async function news(){const now=Math.floor(Date.now()/1000),u=new Map();const rs=await Promise.allSettled(["NASDAQ","NYSE","AMEX"].map(rows));for(const r of rs)if(r.status==="fulfilled")for(const x of r.value){const s=String(x.symbol||x.Symbol||"").toUpperCase().trim(),p=num(x.lastsale??x["Last Sale"]??x.lastSale),v=num(x.volume??x.Volume);if(/^[A-Z]{1,6}$/.test(s)&&p>=1&&p<=7)u.set(s,{price:p,volume:v})}const fs=await Promise.all([feed(GLOBE_RSS,"GlobeNewswire"),feed(PR_RSS,"PR Newswire")]);const out=[],seen=new Set();for(const x of fs.flat()){if(now-x.datetime>86400)continue;const syms=symbols(x.headline+" "+x.summary+" "+x.raw,u),txt=x.headline+" "+x.summary;if(!syms.length||bad(txt)||!catalyst(txt))continue;for(const s of syms){const q=u.get(s),k=s+"|"+x.headline.toLowerCase().replace(/\\W+/g," ");if(!q||seen.has(k))continue;seen.add(k);out.push({symbol:s,headline:x.headline,summary:x.summary,url:x.url,source:x.source,datetime:x.datetime,price:q.price,volume:q.volume,hot:/fda|approval|approved|contract|agreement|acquisition|merger|partnership|award|order|launch|results/i.test(txt)})}}out.sort((a,b)=>Number(b.hot)-Number(a.hot)||b.datetime-a.datetime||b.volume-a.volume);return json({stats:{matching:out.length,lastHour:out.filter(x=>now-x.datetime<=3600).length,hot:out.filter(x=>x.hot).length},items:out.slice(0,50),note:"أخبار شركات مباشرة من GlobeNewswire وPR Newswire، مع فلترة السعر $1-$7."})}
export default{async fetch(request){const u=new URL(request.url);if(u.pathname==="/api/news")return news().catch(e=>json({error:e.message},500));if(u.pathname==="/favicon.ico")return new Response("",{status:204});return new Response(HTML,{headers:{"content-type":"text/html;charset=UTF-8","cache-control":"no-store"}})},async scheduled(){await news().catch(()=>{})}};
